apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: v0.18.1
  name: node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9091"
    prometheus.io/scheme: "http"
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9100
      targetPort: http
    - name: https
      port: 9101
      targetPort: https
  selector:
    app.kubernetes.io/name: node-exporter
